### ISSUE TITLE
[FEAT] Send email for an event happening 12 days from now

### ISSUE THREAD

**Issue by bonelifer** [thomasleplus/google-apps-scripts#4]
`**Feature` description**
I'm disabled. I have to use the local free disability transporter. They only do scheduling for events happening no more than 12 days from when you schedule. I need a reminder that an event is twelve days from now and have it sent to my email so I see it when I check my email. For instance I had an appointment on Tuesday, May 24th. But I have to make the appointment with the transporter no less than 48 hours(business days) in advance. I forgot to call Friday. So I ended up having to reschedule the appointment. It would be nice if all events 12 days in advance from my Doctors calendar got sent in case there is more than one event on a certain date.

**Comment by thomasleplus** [comment]
Hi @bonelifer, I am sure that it can be done. Today the script assumes a calendar named 'Birthdays' because it is the hard-coded name that Google gives to the Google Calendar that imports birthdays from your Google Contacts. But I can certainly write a version of script where the name of the calendar to use is a variable that you could set to whatever works for you. Sending the email 12 days before instead of the same day could also be made a variable that you could change. Does that sound like what you need? Or am I missing something?

**Comment by bonelifer** [comment]
Yes, having it look at the Doctors calendar and sending an email 12 days before a future event is what I'm looking for. I really appreciate your willingness to help me.

**Comment by thomasleplus** [comment]
Sounds good. I have pushed a new version of the script that should do just that. I have also updated their README.md file in the birthday-reminders folder to describe how the change works. You don't need to change the code of the script. You can use script properties to create override the name of the calendar to monitor and the number of days in advance to receive the email. Let me know if it works.

**Comment by bonelifer** [comment]
Could you point me in the right direction of a tutorial on how to setup Google App Script? Ie where in accounts do I go to start this process.

**Comment by bonelifer** [comment]
Ok, I've gotten as far as https://script.google.com
Got as far as setting property, what's the property name for days?
calendarName:Doctors

**Comment by thomasleplus** [comment]
The property name is just 'calendar'. Maybe 'calendarName' would have been a better choice...

**Comment by bonelifer** [comment]
I set property day, is it day or days?
`Execution log
10:07:14 AM
Notice
Execution started
10:07:14 AM
Info
Checking calendar "Doctors"
10:07:14 AM
Info
Searching for date Thu May 26 2022 10:07:14 GMT-0500 (Central Daylight Time)
10:07:14 AM
Notice
Execution completed`

**Comment by bonelifer** [comment]
I do have one question, now that I know it works when I "run" it.  What do I do to set it to run now on it's own?

**Comment by thomasleplus** [comment]
You can use a time-based trigger to run the script daily at the time of your choice. I have put a link to the documentation in the Readme here: https://github.com/thomasleplus/google-apps-scripts/blob/main/birthday-reminders/README.md

Cheers
